### ISSUE TITLE
小鹤双拼方案中发现两个bug

### ISSUE THREAD

**Issue by qianjigit** [BlueSky-07/Shuang#1]
1. 两个空格中，有一个是空的，没显示任何字符，无法下一步
2. 两个空格，一个是 L , 一个是 v 输入正确也无法下一步

**Comment by BlueSky-07** [comment]
1. 没有声母的组合是以韵母开头的拼音，比如 嗯（en） 爱（ai）
2. 已修复
感谢反馈
