### ISSUE TITLE
增加聚焦至输入框的快捷键

### ISSUE THREAD

**Issue by Geeyun-JY3** [BlueSky-07/Shuang#103]
建议增加一个网站全局的，聚焦至输入框的快捷键

**Comment by itchaox** [comment]
> 建议增加一个网站全局的，聚焦至输入框的快捷键

可以去了解下 Chrome 插件（Vimium C - 全键盘操作浏览器），这个可以直接聚焦输入框，直接按 gi 即可

**Comment by itchaox** [comment]
@Geeyun-JY3 刚发现 空格和回车 都能快速聚焦

**Comment by Geeyun-JY3** [comment]
> 刚发现 空格和回车 都能快速聚焦

确实，大意了。
