### ISSUE TITLE
建议把对和错的提示放在拼音后面

### ISSUE THREAD

**Issue by JoySky** [BlueSky-07/Shuang#11]
建议把对和错的提示放在拼音后面，并且换一个现实符号。我在联系过程中发现X（错误符号），跟后边的拼音一样，不便于区分。或者干脆加一个背景颜色来区分。对和错建议放在后边。开始的时候不显示

**Comment by BlueSky-07** [comment]
嗯……是想要和微信小程序相似的正误提示吗，即以换背景色来区分？

**Comment by BlueSky-07** [comment]
对错指示器放在后面如果不移动输入区域，则汉字下面和指示器上面均为空，且在手机设备上宽度不够；
若移动输入区域，则拼音与输入区错位；
汉字放右边不符合正常逻辑；
如果是类似小程序那样，输入区域背景变化指示对错，如果背景宽度等于窗口宽度会显得太长，不协调；
不等于窗口宽度两边留白上下均有留白，不协调。
总之目前UI上的改动没有一个非常理想的方案，所以暂时先不改动。后面想到了再改。
