### ISSUE TITLE
希望自由隐藏或显示拼音提示

### ISSUE THREAD

**Issue by xurayg** [BlueSky-07/Shuang#12]
因为正常打字时，是没有提示的。可以增加一个像隐藏键位图的选框。

**Comment by BlueSky-07** [comment]
正在解决多音字与生僻字无拼音的问题，解决后会添加该功能。

**Comment by BlueSky-07** [comment]
已添加该模式。

**Comment by ethancn** [comment]
现在可以隐藏拼音提示了吗？刚才试了一下没有找到，我也希望可以增加一个选项来隐藏汉字旁边的拼音，这样更接近真实打字的情况。因为我发现自己练习时候盯着那个拼音，键位能飞快地想起来，到实际打字的时候速度又降下来了。😅

**Comment by BlueSky-07** [comment]
练习模式：无拼音
