### ISSUE TITLE
键位图片替换成网页会不会更好

### ISSUE THREAD

**Issue by li01452** [BlueSky-07/Shuang#13]
如题，高分辨率下图片惨不忍睹

**Comment by li01452** [comment]
一个键盘http://jjj666.pw/Keyboard.html

**Comment by BlueSky-07** [comment]
您好，感谢反馈。
为了在手机上也能正常使用，页面上的键位示意图效果不是很好，所以使用了图片。
如果页面做好了会考虑换掉图片。

**Comment by BlueSky-07** [comment]
目前已将图片替换成高清图片，可以看一下效果。
如果图片仍为旧版，可以尝试：右击图片->在新标签页中打开，然后刷新网页后即可更新浏览器缓存。

**Comment by foisonocean** [comment]
可以考虑下 svg 图片，这个在高分辨率下也不会失真
