### ISSUE TITLE
有关搜狗双拼键位的问题

### ISSUE THREAD

**Issue by St3v3Ch3ng** [BlueSky-07/Shuang#14]
首先感谢您提供这么好用的工具

但iOS11中原生搜狗双拼方案应该是包含“；”键吧，希望可以再核查一下。

感谢。

**Comment by BlueSky-07** [comment]
是指键位图上的分号键位置吗？它在第三行最左边，因为第二行摆不下了，而且一般手机上的输入法以分词键替代分号键，位置就与图示一致，所以放在那了。
