### ISSUE TITLE
快速按键时，第二个字母无法出现

### ISSUE THREAD

**Issue by foisonocean** [BlueSky-07/Shuang#15]
在第一个按键还未松开时，按下第二个按键，第二个按键打不出来

**Comment by BlueSky-07** [comment]
打快会卡顿是因为用了两个输入框，输入时会优先判断长度及字符是否合法等，第一格输入过快会被理解成长度在第一格打了两个字符而不会跳到下一格，目前无法优化。但是实际的初学者真正到了这个掌握情况就应该去实际打字而不是再练习啦。

**Comment by foisonocean** [comment]
提了个 PR，帮你修了一下

**Comment by BlueSky-07** [comment]
非常感谢。
经测试，PC端正常，iOS上Safari使用会越来越卡，如何改进？

**Comment by foisonocean** [comment]
@BlueSky-07 你是什么设备？我在 iPad 上测试，没有发现问题

**Comment by BlueSky-07** [comment]
iPhone 6S，iOS 11.0.2，Safari 无痕浏览模式，自带英文输入法；
我的 iPad Air 2（环境与上述相同）上也复现了该问题。
如果您的 iPad 以前打开过该网站，可能会有缓存，可以先访问 
 [https://api.ihint.me/shuang/js/view/core.js](https://api.ihint.me/shuang/js/view/core.js) 更新 js 缓存，如果有此注释则为最新 js：
```
/** last changed: 2017.10.4 */
```
然后访问 [https://api.ihint.me/shuang](https://api.ihint.me/shuang)  刷新3次更新 html 缓存。
或者直接用无痕模式打开 [https://api.ihint.me/shuang](https://api.ihint.me/shuang) 。

**Comment by BlueSky-07** [comment]
嗯……而且现在可以输入以下非法字符：
```
~`-_=+{[}]:"'<,>.?/
```
并且对于有 ; 的方案的判断有问题：第二格输入 ; 没有正确提示的反应，但是按空格键删掉 ; 后有正确提示。

**Comment by BlueSky-07** [comment]
如果修复比较困难的话，我准备换成一个输入框，这样也不会有连打的问题。

**Comment by foisonocean** [comment]
@BlueSky-07 
我是在本地分支开的 simpleHttpServer，所以应该不存在缓存问题，不太清楚到底是什么原因导致的卡顿，在我这里没法复现。
对于那些非法字符，确实是我欠考虑了

**Comment by BlueSky-07** [comment]
还是非常感谢您的帮助。
我已经在着手修改成一个输入框，到时候欢迎提供建议。
