### ISSUE TITLE
增加更多词源

### ISSUE THREAD

**Issue by lijunle** [BlueSky-07/Shuang#18]
我练习一个下午，基本全部字都练了好几次了，后面就没有什么感觉了。希望可以增加更多的字到字典里面。

**Comment by BlueSky-07** [comment]
您好，非常感谢您的反馈。
开发这个工具的目的是想给从没有接触过双拼的人快速入门，所以选配了所有拼音组合的常用字。如果经过多次练习已经可以很熟练的正确输入的话，推荐您把正在使用的输入法换成刚刚学完的双拼，在生活中的打字里不断地打字才可以更熟练地掌握。
