### ISSUE TITLE
Win 7 上的 Chrome 没法用 Enter 和 Space 切下一个字。

### ISSUE THREAD

**Issue by mgdreamingstar** [BlueSky-07/Shuang#19]
按键无法切换下一个。
输入法用 英语-美式键盘，中文输入法是 Rime。

**Comment by BlueSky-07** [comment]
您好，能否提供 Chrome 版本号，选择的双拼方案、练习模式等信息？
在 Chrome 右上角有一个菜单，选择“打开新的隐身窗口”，在黑色浏览器界面里访问 https://api.ihint.me/shuang/ ，看一下能否正常使用？
或者，使用其他浏览器（IE 浏览器需为 IE 9 及以上版本）能否正常使用？

**Comment by mgdreamingstar** [comment]
大牛、自然码方案，练习模式全部随机。
隐身模式正常。
因没有 IE9 以上的其他浏览器，没有进行测试。
另外，在 MacOS High Sierra 上的 Safari 也不能使用。

**Comment by BlueSky-07** [comment]
实在抱歉，不知道哪里出了问题。
如果有更多的人出现了相同的问题，可能会找出BUG。

**Comment by cczhong11** [comment]
我也在https://api.ihint.me/shuang/ 遇到了这个问题。自己在本地运行网页没有问题。自行debug发现是在chrome里没有收到空格和回车,运行这个 ` <body onkeydown="keyAction(event)">` 函数。而是反复输入提交之前的内容。

我在这里加了个log
`
var keyAction = function (event) {
  console.log(event.keyCode);
  switch (event.keyCode) {
    case 13: // Enter
    case 32: // Space
      if (check()) {
        next();
      } else {
        redo();
      }
      break;
  }
};
var inputAction = function (input) {
  input.value = input.value.substr(0, 2).replace(/[^a-zA-Z;]/g, '');
  console.log(input.value);
  check();
};`

![image](https://user-images.githubusercontent.com/7358252/38558518-65a6ff84-3c9e-11e8-9b66-c3d1ad966ea6.png)

前面的log根本看不到，keyAction 在这里根本没有调用。

**Comment by ddkk3000** [comment]
win10 1809 英文输入法状态下也不能按 空格 或者 确认键 换字。
问题同上。chrome 版本 70.0.3538.67

**Comment by BlueSky-07** [comment]
这里需要配合才可以知道出问题的原因：
1. 请在相同环境下去 [http://keycode.info/](http://keycode.info/) 这个页面上按一下空格，然后在此回复页面上出现的数字；
2. 请在打开 [https://api.ihint.me/shuang/](https://api.ihint.me/shuang/) 的页面上按 F12 调出 Chrome 的控制台，然后切换到 Console，重新按流程操作几次后将出错信息贴在回复中。

**Comment by ddkk3000** [comment]
页面上什么数字也不出现呀

________________________________

发件人： BlueSky<mailto:notifications@github.com>
发送时间： 2018-10-24 19:41
收件人： BlueSky-07/Shuang<mailto:Shuang@noreply.github.com>
抄送： ddkk3000<mailto:lixiaozhe@live.com>; Comment<mailto:comment@noreply.github.com>
主题： Re: [BlueSky-07/Shuang] Win 7 上的 Chrome 没法用 Enter 和 Space 切下一个字。 (#19)

这里需要配合才可以知道出问题的原因：

  1.  请在相同环境下去 http://keycode.info/ 这个页面上按一下空格，然后在此回复页面上出现的数字；
  2.  请在打开 https://api.ihint.me/shuang/ 的页面上按 F12 调出 Chrome 的控制台，然后切换到 Console，重新按流程操作几次后将出错信息贴在回复中。

**Comment by cczhong11** [comment]
我也是没有出现任何数字。使用无痕模式可以出现32.

**Comment by BlueSky-07** [comment]
更换了按键触发机制，请在此体验 [https://api.ihint.me/shuang/beta/](https://api.ihint.me/shuang/beta/) 后跟进回复问题是否已解决。

**Comment by cczhong11** [comment]
Works for me. 非常感谢！

**Comment by ddkk3000** [comment]
我的也可以用了，感谢

________________________________
╭( ′• o •′ )╭☞ lixiaozhe.com

发件人： tianchen zhong<mailto:notifications@github.com>
发送时间： 2018-10-24 20:16
收件人： BlueSky-07/Shuang<mailto:Shuang@noreply.github.com>
抄送： ddkk3000<mailto:lixiaozhe@live.com>; Comment<mailto:comment@noreply.github.com>
主题： Re: [BlueSky-07/Shuang] Win 7 上的 Chrome 没法用 Enter 和 Space 切下一个字。 (#19)

Works for me. 非常感谢！
