### ISSUE TITLE
能否提供一个省略简单音节的版本

### ISSUE THREAD

**Issue by iamCristYe** [BlueSky-07/Shuang#2]
有些两字母音节比较简单，比如（以小鹤为例）

1. 单音节，如啊（aa）、哦（oo）
2. 声母和韵母都是单字母，如你（ni）、我（wo）
3. 双字母韵母，如诶（ei）、欧（ou）

这些都比较简单，所以不想让它们在练习时出现……能否提供一个这样的选项？

**Comment by BlueSky-07** [comment]
感谢反馈
已添加该模式

**Comment by iamCristYe** [comment]
Thx!
