### ISSUE TITLE
发现个bug！

### ISSUE THREAD

**Issue by axhello** [BlueSky-07/Shuang#22]
发现个bug！ 有个字 `俩 ` 无法回车
![ll](https://user-images.githubusercontent.com/10368684/33205758-10361100-d143-11e7-876a-910eb50f7a5a.png)

**Comment by BlueSky-07** [comment]
您好，非常感谢您的反馈。
俩（lia / liang）这是个多音字，忘记在无拼音模式中去掉了，将会在下个版本里修复。
