### ISSUE TITLE
拆分练习模式

### ISSUE THREAD

**Issue by iamCristYe** [BlueSky-07/Shuang#23]
建议拆分目前的练习模式为三个选项：
联系范围：全部/困难
联系顺序：随机/按序
显示拼音：显示/隐藏

**Comment by BlueSky-07** [comment]
现有的是 4 套模式，如果修改就变成了 8 套。
4 套模式是循序渐进、逐渐入门的过程，8 套中有一些似乎没有必要设置了。

**Comment by iamCristYe** [comment]
行吧
