### ISSUE TITLE
1个小问题和2个小建议

### ISSUE THREAD

**Issue by zhangyuhangk** [BlueSky-07/Shuang#24]
这个软件确实很方便，练习起来很顺手。感谢作者！

1个小问题：
- 有时会卡住。此时的输入会延迟几秒再出来。(Win 7 + Firefox 59.0.1)

2个小建议
- 练习模式可以增加分区的练习。比如只练习ang, an, ao, ai 等等键位，这样短时间重复率高，更容易记住（练五笔时的经验）
- 手机上的小程序希望能选择九宫格模式。

**Comment by BlueSky-07** [comment]
感谢您的反馈！
1.卡住是在切换下一题且题目变更完成后，此时立即输入卡住吗？还是题目变更完成以后，有一个间断后输入才卡住？
2.选择固定韵母练习是自选韵母范围吗？如果是这样的话，选择界面如何做的简单易用设计起来会比较难。而且有些韵母可能是某些声母特有的，如果用户选择的韵母集合不包含该声母的话会漏练，如果集合里元素较少且包含该声母会大量重复练习。如何设计这些还是需要考虑一下的。
如果可能的话，最佳方案是做自动推荐练习，将所有韵母周期地、完整地循环练习，错的强化练习增加出现频率，对的减少出现频率。不过由于个人能力有限，实现起来任重道远，所以目前只好设定4种模式，新手按照模式次序，先全部顺序，再困难随机，再无拼音，也有循序渐进的过程。
3.九宫格模式是将键位图改成9宫格吗？还是输入9宫格的数字？
前者的话，手机屏幕较小，放9宫格键位图难以排版，做不到在能看得清图片的基础上不被系统键盘遮挡。
后者的话，其实违背了双拼韵母与唯一按键绑定的原则，实际用9宫格打双拼会有非常多的重码，选词非常琐碎耗时。
欢迎回复讨论。
