### ISSUE TITLE
有整句输入训练吗？

### ISSUE THREAD

**Issue by reaCodes** [BlueSky-07/Shuang#30]
单字输入训练太单一了吧，打字的时候一般都是整句输入

**Comment by BlueSky-07** [comment]
目前还没有计划做整句输入练习。
开发这个工具的目的是想给从没有接触过双拼的人快速入门，所以选配了所有拼音组合的常用字。如果经过多次练习已经可以很熟练的正确输入的话，推荐使用者把正在使用的输入法换成刚刚学完的双拼，在生活中的打字里不断地打字才可以更熟练地掌握。
