### ISSUE TITLE
提供超时按键提示

### ISSUE THREAD

**Issue by eternal-flame-AD** [BlueSky-07/Shuang#31]
类似 #21 设置一个超时，超过一定时间没有打出韵母则提示一下，不用打开键位图，增强一点节奏感

**Comment by BlueSky-07** [comment]
好的，后续版本添加该功能。

**Comment by BlueSky-07** [comment]
已经添加了该功能。
不过不是超时的自动提示，因为这样可能会打扰用户实时的输入体验。
目前的方案是设置成按 Tab 键显示答案。

**Comment by eternal-flame-AD** [comment]
很好用，感谢
