### ISSUE TITLE
发现一个网站用于商业用途

### ISSUE THREAD

**Issue by SeanRao** [BlueSky-07/Shuang#33]
http://www.matools.com/nicetool-shuangpin
![image](https://user-images.githubusercontent.com/32856349/49195712-32b9a680-f3c3-11e8-82ac-015c771c00ba.png)

**Comment by BlueSky-07** [comment]
:confounded: 很无奈

**Comment by SeanRao** [comment]
> 😖 很无奈

发现简直了，再搜索多几下出现好几个这样做的网址。。。现在的人为了钱也是可以了

**Comment by RubiTree** [comment]
作者一开始没有加license吧... 没办法...
