### ISSUE TITLE
可以考虑下加入一个特定键位练习的功能

### ISSUE THREAD

**Issue by LasyIsLazy** [BlueSky-07/Shuang#37]
刚上手时，可能一下练习26个键位不容易记住。可以考虑下只练习某一个区域或者某几个键的方案。

**Comment by BlueSky-07** [comment]
可以 后续版本可能加入

**Comment by rywiki** [comment]
初学需要反复

**Comment by HongYang57** [comment]
Bluesky你好，我和楼主有类似的感受。

简单讲就是打字按键可以慢慢覆盖整个键盘，而不是一上来就遍历所有按键。

比如，一开始程序只让用户打有关某一个韵母的字，比如eng的字，如“碰”“朋”“蹦”，不断地告诉用户eng是g键，eng是g键，用户打的熟练了打的快了，再加一个新按钮，这样一点一点增加，效果会好很多。

这个idea源于这个网站https://www.keybr.com/ ，你可以看一下

感谢
