### ISSUE TITLE
请问可否加入整句练习功能？

### ISSUE THREAD

**Issue by likeSo** [BlueSky-07/Shuang#38]
一段话，或者一篇文章，一首诗，可以从其他书籍中摘录，然后可以记录一下整句的打字速度啥的，达到实践的效果。
我感觉我现在练习单字已经很6了，但是打字速度还是跟不上去🌚

**Comment by BlueSky-07** [comment]
以后会加的，最近没啥时间……
其实最好的练习方式是把输入法切成双拼然后在日常生活中输入使用，孰能生巧，3天左右就能记住啦 😎

**Comment by likeSo** [comment]
NBNB👏主要是想找一个地方，让自己联系&享受打字的感觉，练一练打字速度
我还有一个问题，微信小程序版本有一个“正确自动切换”功能挺不错的，Web版能否也加入这个设置？

**Comment by BlueSky-07** [comment]
字帖：[https://api.ihint.me/zi](https://api.ihint.me/zi)
欢迎体验 & 提建议

**Comment by likeSo** [comment]
厉害了老哥，给你个参考 http://typing.sjz.io/#/article 😊，这个好像也是独立作品，就是好像还没有全部完成~

**Comment by BlueSky-07** [comment]
应该不会做成这么复杂的系统，
应该最终会做成像双拼练习这样仅保留最核心功能的工具，可以让用户沉浸于练习/学习，不关心速度。

**Comment by likeSo** [comment]
我本来想提的需求是，web端也加入小程序端的“正确自动切换”的功能，因为要想达到熟能生巧的地步，速度就少不了啊，要形成肌肉记忆呀😂
但是觉得加入了自动切换还是有一个问题，因为每个练习的单字不连贯，无法模拟真实的打字场景。所以老哥考虑一下吧😁

**Comment by BlueSky-07** [comment]
相关功能已添加。

**Comment by likeSo** [comment]
🐂🍺！！
