### ISSUE TITLE
[BUG] <select> wrong color in dark mode on Safari

### ISSUE THREAD

**Issue by magic-akari** [BlueSky-07/Shuang#40]
https://github.com/BlueSky-07/Shuang/blob/7124b3a3aaf2d9e37b94745ddd40da20a483630e/src/style.css#L270-L277

看起来这是专门给 Safari 的 CSS 规则，
但是请问出于何种考虑，要让 `<select>` 元素的颜色在 dark mode 下显示黑色呢？

![image](https://user-images.githubusercontent.com/7829098/53315090-86715880-38fc-11e9-912a-ea4a896ec9b2.png)

移除这个规则的话，会显得正常得多：
![image](https://user-images.githubusercontent.com/7829098/53315188-fa136580-38fc-11e9-9eb4-0bec7e9261d0.png)

Browser UA: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15`

**Comment by BlueSky-07** [comment]
这个样式是给 iOS 端的 Safari 使用的。
可以用屏幕尺寸来判断是否是移动设备，下个版本修复。

**Comment by BlueSky-07** [comment]
我现在手边没有 Mac 设备，可以帮我测试一下吗：
[https://api.ihint.me/shuang-debug/](https://api.ihint.me/shuang-debug/)

**Comment by magic-akari** [comment]
> 我现在手边没有 Mac 设备，可以帮我测试一下吗：
> https://api.ihint.me/shuang-debug/

OK 了

**Comment by magic-akari** [comment]
但是我觉得根据宽度来判定不是个好主意， iOS 下为什么需要黑色字体？
