### ISSUE TITLE
建议加入简单的统计功能

### ISSUE THREAD

**Issue by RubiTree** [BlueSky-07/Shuang#42]
首先非常感谢您的项目，刚刚学习双拼，您的项目让我收获很大！

只需要几个简单的统计，初学者就能很直观地看到自己的一点点进步，快速反馈，从而让初学者更有信心学下去

个人建议一开始只需要加入：
1、本次总输入
2、当前每分钟输入个数（当前时间到过去一分钟的）

以后有空可以加入一个图表

暂时可以不建立账户体系，就统计当前次的输入情况就好

**Comment by BlueSky-07** [comment]
以后有空再加。
其实初学者上手之后不应再执着于练习，而是在日常生活中使用，以此来掌握，日积月累打字速度自然就会快了。

**Comment by RubiTree** [comment]
> 以后有空再加。
> 其实初学者上手之后不应再执着于练习，而是在日常生活中使用，以此来掌握，日积月累打字速度自然就会快了。

感谢回复
不过我目前初学时候遇到的问题是：切换成本比较大。
因为日常工作还是比较忙的，不能一下切换过去，希望用空闲时间多练习，到一定程度后再切...
不知道这种方式是不是永远学不会双拼... 但目前我的情况是这样 Orz
