### ISSUE TITLE
建议增加注音

### ISSUE THREAD

**Issue by davix** [BlueSky-07/Shuang#43]
注音符号是拼音发布前中国人的汉字标音方案，台湾至今在用，大陆也有使用（如新华字字典一直都有）。
从方案本身看，实际是三拼，因韵母可能为零或一或二个。全部键都分布在键盘，没有复用。
建议增加支持，参考布局如下：
https://github.com/davix/keyboard-bopomofo-pinyin

**Comment by BlueSky-07** [comment]
你好：
首先哈，我没用过注音输入法，但是大概了解一些。注音输入本身的话不是每次都是击键两次的，而这个工具无论是开发目的还是代码设计，都是为两次击键的双拼输入服务的，非两次击键的方案与其无法兼容。也就是说可能需要大量时间重新架构代码，或者重写，工作量都不小。
然后呢，关于参考链接里的内容，我没太看懂这张图片：[keyboard-bopomofo-pinyin.png](https://github.com/davix/keyboard-bopomofo-pinyin/blob/master/keyboard-bopomofo-pinyin.png)，这个是基于 QWERTY 的键位图吗？
最后，我近期没有时间和精力开发新功能，如果可以的话欢迎提 PR。

**Comment by davix** [comment]
好，明白。图片是qwerty的，跟这个是一样的：https://commons.wikimedia.org/wiki/File:Keyboard_layout_Zhuyin.svg#/media/File:Keyboard_layout_Zhuyin.svg

**Comment by trevim99** [comment]
> 注音符号是拼音发布前中国人的汉字标音方案，台湾至今在用，大陆也有使用（如新华字字典一直都有）。 从方案本身看，实际是三拼，因韵母可能为零或一或二个。全部键都分布在键盘，没有复用。 建议增加支持，参考布局如下： https://github.com/davix/keyboard-bopomofo-pinyin


大家好

小鶴雙拼 + 注音 ㄅ ㄆ ㄇ ㄈ 的鍵位對照圖，請參考喔，謝謝

<img width="812" alt="有ㄩPixPin_2024-09-05_08-01-05" src="https://github.com/user-attachments/assets/ea3d3ae6-3010-4245-beb3-06bcb4124a0d">

**Comment by BlueSky-07** [comment]
关于在双拼练习项目里添加注音符号的建议，现在的键位图设计里没有放置除了zh/ch/sh以外韵母的例子。
如果后续添加注音符号的话，会考虑在右上角放上声母，下面放韵母，左上角的英文字母保留，但例字不会放进去。

**Comment by BlueSky-07** [comment]
已更新切换注音符号模式

**Comment by trevim99** [comment]
> 已更新切换注音符号模式


谢谢大佬👍，已成功启用🙏🙏
谢谢


![image](https://github.com/user-attachments/assets/5d141594-c0d8-4945-9ae8-5bdc9e3a7d01)

![image](https://github.com/user-attachments/assets/1abe817f-a739-4fbf-823d-4198caa37486)

**Comment by davix** [comment]
注音最常見的佈局是大千式的（所有系統內置的），可以支持嗎？

**Comment by BlueSky-07** [comment]
> 注音最常見的佈局是大千式的（所有系統內置的），可以支持嗎？

看了维基百科https://zh.wikipedia.org/wiki/%E6%B3%A8%E9%9F%B3%E8%BC%B8%E5%85%A5%E6%B3%95#%E5%A4%A7%E5%8D%83%E6%B3%A8%E9%9F%B3%E9%8D%B5%E7%9B%A4%E6%8E%92%E5%88%97 大千式键盘的英文字母布局也是QWERTY的，现在的实现方式也是在QWERTY布局的键盘上添加双拼方案的汉语拼音对应的注音符号，和楼上 @trevim99 提供的设计图类似，感觉没什么问题
