### ISSUE TITLE
ios12 越狱能不能也使用原生的自然码布局呢

### ISSUE THREAD

**Issue by 7ack** [BlueSky-07/Shuang#44]
感谢分享mac使用原生自然码输入,用了那么久第三方终于可以使用原生的了.
因为ios原生键盘支持的功能更多,但是不支持自然码,打算换成拼音加加才发现的这个项目.
请问,ios12越狱了能更换成自然码的布局吗?

**Comment by BlueSky-07** [comment]
这个好像没办法，只能等苹果更新系统来支持。

**Comment by BlueSky-07** [comment]
可以试一下：https://sspai.com/post/60751
