### ISSUE TITLE
小鹤双拼的零声母有两种方式输入

### ISSUE THREAD

**Issue by zhuxiaoxi** [BlueSky-07/Shuang#46]
小鹤对于`ai` `en`这种2字母的零声母音节（除`er`）有两种输入方式，建议添加。
比如`ai` = `ai` or `ad`
`en` = `en` or `ef`
受影响的包括：`ai` `an` `ao` `ei` `en` `ou`

**Comment by BlueSky-07** [comment]
官网不是这么写的呀：[https://www.flypy.com/pin.html](https://www.flypy.com/pin.html)

**Comment by zhuxiaoxi** [comment]
测试了，包括iOS和Rime都可以做到。

**Comment by BlueSky-07** [comment]
以官方说明为准
