### ISSUE TITLE
双拼联系页UI建议

### ISSUE THREAD

**Issue by BetatoGamma** [BlueSky-07/Shuang#49]
建议增加选项：允许用户开启或关闭全拼显示。
理由：练习打字的“目标”就是眼睛看见字，手指自然的就去敲击对应的按键。因为全拼的存在加上双拼输入框在全拼下面，输入的时候，眼睛会情不自禁的看全拼而不是看字，这与”目标“所期望的结果不符。所以，建议增加开关允许用户关闭全拼，以实现眼看字手敲击的完美过程！

**Comment by BlueSky-07** [comment]
可以切换到“无拼音”模式
