### ISSUE TITLE
强烈建议增加一个韵母键位联系

### ISSUE THREAD

**Issue by smart-z** [BlueSky-07/Shuang#52]
[img](https://ftp.bmp.ovh/imgs/2019/09/0811c001bcaa3cb2.png)

https://ftp.bmp.ovh/imgs/2019/09/0811c001bcaa3cb2.png

对新手来说，重点是明白韵母的键位。我试了两天您的工具，其中一个特别浪费时间的事情就是每敲一个字我都要花费1-5秒的时间找韵母的键位。

请务必考虑，不会插图，请点链接看看，我做了一个小修改，显示字的地方换成了韵母和对应的键位。

**Comment by BlueSky-07** [comment]
似乎看不出“题目”应该放哪？
或者说，是想添加一个模式只练习复韵母？
