### ISSUE TITLE
希望增加显示键位的功能（在键盘图上）

### ISSUE THREAD

**Issue by kasusa** [BlueSky-07/Shuang#57]
可以参考一下这个图片
[来自typingclub](https://wx2.sinaimg.cn/mw690/006rgJELgy1gaq2ejtv34j30m80k6aen.jpg)
其实这个对于新手来说真的非常非常的重要。
因为主要就是记不住在哪里。点一下tab键实际上还是不方便的。。

**Comment by BlueSky-07** [comment]
有考虑做成这样：https://www.keybr.com/

**Comment by tldzyx** [comment]
没有形成肌肉记忆之前, 每次眼球在键位图上找韵母的确不利于练习.

**Comment by BlueSky-07** [comment]
该功能已经上线
