### ISSUE TITLE
不同方案不同键盘布局显示

### ISSUE THREAD

**Issue by Tenderest** [BlueSky-07/Shuang#58]
就是我今天使用的时候发现 _切换不了显示的键盘布局_ ，我选择的是**自然码**，键盘布局是 **Dvorak**，而自然码的布局只有`QWERTY`的显示，我简单看了一下发现显示的是一张图片，然后想自己手动替换一下，找到了左下角那个键位图的网站，但是发现没有替换的方法。所以就来问问看有无解决办法，就是添加一下 *不同布局下的不同方案* 的显示，可以让用户选择。万分感谢。

**Comment by BlueSky-07** [comment]
因为现在增加了按键提示的功能，增加 Dvorak 的键盘布局图案的话还需要一些额外的开发，但是由于 Dvorak 的用户过于小众了，所以不打算做这个定制开发。
如果有能力的话可以自己尝试一下增加这个功能，然后提一个 PR。

**Comment by weakish** [comment]
@Tenderest 左下角的网站是作者用 React 画了一套键位图，而这个练习打字的网站并没有用，而是用图片显示键位图。最快的替换方法是把 `img/ziranma.png` 替换为 Dvorak 布局的自然码键位图（可以到网上找一张，或者直接到左下角的网站去截个屏），同时练习时关闭「显示按键提示」。

**Comment by BlueSky-07** [comment]
已更新
