### ISSUE TITLE
关于 智能ABC 方案 "ve" 添加 "m" 的说明

### ISSUE THREAD

**Issue by BlueSky-07** [BlueSky-07/Shuang#65]
有用户提到
> 程序里面的智能ABC方案将ve分配给了v键，但在我使用Mac OS Catalina 和Windows 10中的系统默认双拼输入法的经验看，他们两大系统都已经纠正了这个瑕疵，不管是ve还是ue都用m键来输入

经过测试发现：

1. 在 macOS 10.15.4 上测试了一下，m 和 v 两种方式都是可以输入的：
![image](https://user-images.githubusercontent.com/17378243/80891696-47a51280-8cf8-11ea-9d5c-6dba5431945c.png)

2. 在 iOS Gboard 上测试了一下，只支持 m：
![image](https://user-images.githubusercontent.com/17378243/80891700-4d9af380-8cf8-11ea-9b78-0e5b43a2cfd7.png)

3. 在 Windows 10 上测试了一下，也是只支持 m：
![image](https://user-images.githubusercontent.com/17378243/80891703-51c71100-8cf8-11ea-82af-117e93879b86.png)

-----------

由于现在打不开 [智能ABC输入法的官网](http://www.znabc.com/) 来查看官方说明了，从 [Wikipedia-智能ABC输入法](https://zh.wikipedia.org/wiki/%E6%99%BA%E8%83%BDABC%E8%BE%93%E5%85%A5%E6%B3%95) 词条上看确实只有 v 的样子，综合考虑的话会改成 v、m 判定都通过。

**Comment by wwzrh** [comment]
强烈要求把 "ve" 调整为 "m"，虽然智能ABC输入法的官网关了，经调查：微软拼音、百度拼音，特别windowsXP系统的智能ABC和网络可下载的“智能ABC 5.23输入法 ”的帮助文档都是在"m"键，而不是V键。
