### ISSUE TITLE
最新版的detectDarkMode().toString()报错，detectDarkMode()返回的是null

### ISSUE THREAD

**Issue by yunzhongjushi** [BlueSky-07/Shuang#66]
最新版的detectDarkMode().toString()报错，detectDarkMode()返回的是null

**Comment by SaulHE** [comment]
## 当前的情况
当用户的浏览器无法满足下列条件的任何一种情况时。网页会出现下列报错：
`Uncaught TypeError: Cannot read property 'toString' of undefined`
导致网页的功能无法运行（截图如下）：
![image](https://user-images.githubusercontent.com/51215850/80968307-50a5f900-8e4a-11ea-9f9b-33bca4e74a95.png)


## 预期的情况
没有bug

## 问题代码定位
```javascript
function detectDarkMode() {
  if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
    return true
  }
  if (new Date().getHours() < 6 || new Date().getHours() > 22) {
    return true
  }
}
```
在默认情况下，返回为null
应当添加默认return

## 相关的修复PR：
[https://github.com/BlueSky-07/Shuang/pull/67/files](url)

**Comment by BlueSky-07** [comment]
已修复 感谢 @SaulHE
