### ISSUE TITLE
Ubuntu Distribution Linux  bash couldn't recognize scripts/build-app.sh

### ISSUE THREAD

**Issue by SaulHE** [BlueSky-07/Shuang#68]
# Current Behaviour
When the project is built in Ubuntu Distribution Linux, bash wouldn't recognize the script in the right format.

With the following Error Prompt:

```
scripts/build-app.sh: 3: scripts/build-app.sh: Syntax error: "(" unexpected
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! shuang@5.9.0 build:app: `scripts/build-app.sh`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the shuang@5.9.0 build:app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

# Error Screenshot
![image](https://user-images.githubusercontent.com/51215850/80970278-7c76ae00-8e4d-11ea-8a7c-3daafeaf5307.png)

# A fix attempt:
Add a shebang line.

# Fix PR:

[https://github.com/BlueSky-07/Shuang/pull/67](url)

**Comment by BlueSky-07** [comment]
已修复
