### ISSUE TITLE
回车下一题

### ISSUE THREAD

**Issue by xurayg** [BlueSky-07/Shuang#7]
回车不会下一题，希望可以支持。

**Comment by BlueSky-07** [comment]
一直支持回车键或空格键下一题的。
是不是用了中文输入法？切换至英文输入法，或者英文输入模式使用。
是不是输错了呢？能否提供一下不能下一题的方案及题目？
如果仍有问题，请尽可能多地提供使用环境，以便修复：
1. 使用终端：手机？电脑？
2. 系统版本：Android/iOS？Windows/macOS？
3. 浏览器信息：手机自带浏览器？Chrome/Safari/Firefox/IE？
4. 浏览器版本号；
5. 使用的输入法：英文输入法？某个中文输入法的英文模式？
6. 其他对解决问题有帮助的信息。

**Comment by xurayg** [comment]
Mac系统10.12.6
Safari浏览器10.1.2
系统自带英文输入法

**Comment by BlueSky-07** [comment]
经多台机器测试，问题均没有复现。
请确认使用的是系统自带“ABC”输入法。
![tim 20170909114309](https://user-images.githubusercontent.com/17378243/30236766-3964e2c0-9554-11e7-95ae-f85ea3513f74.jpg)

**Comment by xurayg** [comment]
<img width="257" alt="2017-09-09 14 19 31" src="https://user-images.githubusercontent.com/7018319/30237681-f8f1533e-9569-11e7-844e-161f92fe31b3.png">
美国 和 abc 两个都试了，都不能回车下一题。。

**Comment by BlueSky-07** [comment]
经过测试，应该为浏览器缓存问题。现在已将网页端更新为强制刷新，应该可以解决问题了。如不能，请再回复。

**Comment by BlueSky-07** [comment]
在一台机器上问题复现了，现已修复该BUG。请连续刷新网页3次以确认缓存被刷新，然后请尝试使用。还请麻烦再次回复以便告知是否问题被解决。

**Comment by xurayg** [comment]
已解决～
