### ISSUE TITLE
建议添加单独的韵母及zh ch sh键位练习

### ISSUE THREAD

**Issue by xiebruce** [BlueSky-07/Shuang#70]
第一天学双拼，其实学双拼就是记韵母+zh ch sh的键位，所以建议添加一个单独练习韵母+zh ch sh键位的功能，不打具体的字，就单独练习键位。我这段话就是用小鹤双拼打的，但由于不熟悉韵母+zh ch sh键位，打的我很抓狂哈哈。

**Comment by sunset-warrior** [comment]
附议

**Comment by BlueSky-07** [comment]
没有这个必要，声母键比韵母键少得多

**Comment by xiebruce** [comment]
@BlueSky-07 你没看清楚，我说的是“韵母”+“zh ch sh”，主要是韵母呀，只有zh ch sh是声母
