### ISSUE TITLE
键道3双拼方案v韵母问题

### ISSUE THREAD

**Issue by R0uter** [BlueSky-07/Shuang#8]
在键道3中：
xu=xv ，是不正确的。
xu=xl， 不是xm
ju=jl，
qu=ql，
yu=yl

v用原形，不用u

：）

**Comment by R0uter** [comment]
我通过模糊l键的v和u来处理了这个问题，但这样也导致原本错误的情况依旧是正确的。具体可能还是需要老哥你来考虑要不要为键道3添加一个额外的判断了。

**Comment by BlueSky-07** [comment]
了解了，那么大牛双拼里处理的可能也不正确。

**Comment by BlueSky-07** [comment]
那么有一个问题：拼音提示上会对用户造成误导，比如 xu ，初学者第一想法是去找 u 的双拼码，而不会去找 v；
类似还有 xue，不写做 xve；yuan 不写做 yvan。

**Comment by R0uter** [comment]
这就比较尴尬了，这是一个哲学问题，我做输入法的时候也遇到了这个情况，究竟在遇到jqx的时候，是应该算u还是算v，这两种办法都存在且都对。我最后是模糊处理了，这里我也不知道你该怎么去处理。我去问问大牛本人。

**Comment by BlueSky-07** [comment]
常见输入法对于普通双拼方案的设置上基本上都是模糊处理，比如搜狗输入法PC版-智能ABC方案，需(xu)可用xu/xv，学(xue)可用xv/xm，这样的话xv的候选词里有xu和xue两者的字。
这样的处理应该算作是程序开发友好型的吧，哈哈。估计方案的作者不太愿意看到这样的结果。但是另一方面也有一个问题，就是方案的作者在把方案添加到类似于搜狗输入法上面的时候该怎么处理呢？

**Comment by R0uter** [comment]
这是键道的搜狗配置，你参考下吧，实在不行就先这样咯。
```
[metadata]
title=º¸µ¿3

[…˘ƒ∏]
zh=f
ch=w
sh=e
zr=q
cr=j

[‘œƒ∏]
ing=g
iao=q
ang=h
an=e
ai=f
ue=f
ve=f
ie=c
ua=c
ao=z
ian=d
uai=d
ui=b
in=b
iang=x
uang=x
iu=s
ei=w
uan=r
van=r
un=w
vn=w
uo=l
ong=y
iong=y
en=n
eng=t
ou=s
a=p
ia=p
er=n
i=k
o=l
v=l
e=j
u=m

[¡„…˘ƒ∏“ÙΩ⁄µƒ‘œƒ∏]
a=xp
ai=xf
an=xe
ang=xh
ao=xz
e=xj
ei=xw
en=xn
eng=xt
er=xm
o=xl
ou=xs

```

**Comment by BlueSky-07** [comment]
好的，谢啦。

**Comment by R0uter** [comment]
ok，回头我再给你加更多方案进去，我这里很多嘿嘿。

**Comment by R0uter** [comment]
另外我要吐槽你变量竟然不用英文用双拼，我猜了好久才猜出来应该是自然码……

**Comment by BlueSky-07** [comment]
嘿嘿，一时间没想到声母/韵母单词长啥样，然后顺手写成了自然码，也算是小彩蛋啦。

**Comment by R0uter** [comment]
在音节避重规则中有一条：v用韵母原形
大牛  12:33:25
在搜狗、手心等智能平台中，v韵母，都可以用原形来拼，但在星空键道中，直接规定v韵母能且只能用原形与jqx相拼。 但这会不会影响拼音的规范性呢？ 我们可以理解为星空键道的拼音是一个动态的过程：在拼合时，我们取用的是韵母表中的韵母原形v，当它与jqxy相遇时，立即就变成了合乎书写规则的音节ju qu xu yu，也就是说，软件的显示，仍然是采用符合书写规范的音节形式。而传统的方法，我们可以理解为把书写出来的规范音节拆开又拼拢的过程，音节形式没有任何变化，是一种静态的过程。 我们认为，动态的拼合形式，反而有利于人们掌握韵母表和拼写规则，因而同样是合乎规范的。


————————
这是大牛在键道文章中的相关部分，他是这么理解的。

**Comment by BlueSky-07** [comment]
今天重写了整个项目的js代码，目前提供了可供实现适应不同方案的特殊要求的判断：
思路是
1. model().isTeuu = true;
2. model().scheme_teuu = [{ugmu}, {ypmu}]
目前还没实现具体方案的细节，先休息了。

**Comment by R0uter** [comment]
666

**Comment by BlueSky-07** [comment]
所有需求都实现了，上线等有无BUG反馈。
明天开始改微信小程序。
