### ISSUE TITLE
支持Colemak-DH布局

### ISSUE THREAD

**Issue by pingshunhuangalex** [BlueSky-07/Shuang#80]
希望能够增加Colemak-DH布局以帮助练习

如果觉得不合适的话 至少希望能够增加自定义布局的选项 谢谢

**Comment by BlueSky-07** [comment]
目前没有增加其他键盘布局支持的开发计划，不过欢迎提 PR！

**Comment by Inc0n** [comment]
![双拼键位图colemakdh](https://github.com/user-attachments/assets/a2506b4e-3e58-4685-a8d6-50906ce0d73d)
这样可以吗？

**Comment by BlueSky-07** [comment]
已更新
